config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact_us' => 'pages#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_us_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We're working on our One Month Rails project.
I'm an old school RDBMS developer who really wants to keep my hands on the web these days.
Due to different reasons of course.
</p>

app/views/pages/contact_us.html.erb
<h1>Contact Us</h1>
<p>We are availabel 24/7 through the phone help lines.
You can also call our customer services department if you are having a questions.
Otherwise we will reach out to you if you would drop us a line.
</p>

app/views/pages/home.html.erb
<h1>Welcome to my First Ever Website!</h1>
<p> This is a test Web Site to see how Ruby on Rails Work. 
	This is interesting to know all these happens.
	Fantastic.
	Beautiful :)<p>
<p>Sign Up Here.</p>